# Generated by Django 5.2 on 2025-04-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.customuser',),
        ),
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.customuser',),
        ),
        migrations.CreateModel(
            name='MemberUser',
            fields=[
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.customuser',),
        ),
    ]
